version: '3.3'

services:

  api:
    container_name: evolution_api
    image: youngkhaf/yk-evolution
    restart: always
    ports:
      - 3400:3400
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    env_file:
      - .env
    command: ['node', './dist/src/main.js']
    expose:
      - 3400
    networks:
      - shared_services

volumes:
  evolution_instances:
  evolution_store:

networks:
  shared_services:
    external: true
