version: '3.3'

services:

  mongodb:
    container_name: mongodb
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb:/data/configdb
    expose:
      - 27017
    networks:
      - shared_services

  mongo-express:
    container_name: mongodb-express
    image: mongo-express
    restart: always
    ports:
      - 8100:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongodb
    networks:
      - shared_services

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    ports:
      - 6900:6379
    command: >
      redis-server
      --port 6900
      --appendonly yes
    volumes:
      - redis:/data
    networks:
      - shared_services





volumes:
  mongodb_data:
  mongodb_configdb:
  redis:

networks:
  shared_services:
    external: true
      
